package com.example.model.enums;

public enum Symptoms {
    FATIGUE, THIRST, INSOMNIA, DRY_SKIN, HAND_SHAKING, FEVER,
    HEADACHE, HAIR_LOSS, RAPID_HEART_RATE, SKIN_RASH,
    FREQUENT_URINATION, IRREGULAR_PERIODS, NAUSEA_VOMITING,
    VISION_DISTURBANCE, JOINT_PAIN, JOINT_SWELLING,
    MOOD_CHANGES, WEIGHT_GAIN, WEIGHT_LOSS, HEAT_SENSITIVITY,
}
