package rules.bloodTestRequest;

import com.example.model.Patient;
import com.example.model.enums.BloodTestType;
import com.example.model.BloodTestAnalysis;
import com.example.model.Disease;
import com.example.model.enums.Symptoms;

import java.util.List;
import java.util.ArrayList;
import java.time.LocalDate;
import java.util.Arrays;

global java.util.List allDiseases;


rule "Request blood tests for Hashimoto disease"
	agenda-group "blood tests"
when
    $patient : Patient()
    $symptoms : List()
    $disease : Disease(name == "Hashimoto") from allDiseases
    $count : Number() from accumulate(
        $symptom : Symptoms(this memberOf $disease.getSymptoms()) from $symptoms,
        count($symptom)
    )
    eval($count.doubleValue() >= 1)
    $testType : BloodTestType() from $disease.getBloodTests()
    not(exists BloodTestAnalysis(type == $testType, date == LocalDate.now()) from $patient.getBloodTestAnalyses())
then
    $patient.addBloodTestAnalysis($testType);
end;


rule "Request blood tests for Graves disease"
	agenda-group "blood tests"
when
    $patient : Patient()
    $symptoms : List()
    $disease : Disease(name == "Graves") from allDiseases
    $count : Number() from accumulate(
        $symptom : Symptoms(this memberOf $disease.getSymptoms()) from $symptoms,
        count($symptom)
    )
    eval($count.doubleValue() >= 1)
    $testType : BloodTestType() from $disease.getBloodTests()
    not(exists BloodTestAnalysis(type == $testType, date == LocalDate.now()) from $patient.getBloodTestAnalyses())
then
    $patient.addBloodTestAnalysis($testType);
end;

rule "Request blood tests for Systemic Lupus Erythematosus (SLE)"
	agenda-group "blood tests"
when
    $patient : Patient()
    $symptoms : List()
    $disease : Disease(name == "SLE") from allDiseases
    $count : Number() from accumulate(
        $symptom : Symptoms(this memberOf $disease.getSymptoms()) from $symptoms,
        count($symptom)
    )
    eval($count.doubleValue() >= 1)
    $testType : BloodTestType() from $disease.getBloodTests()
    not(exists BloodTestAnalysis(type == $testType, date == LocalDate.now()) from $patient.getBloodTestAnalyses())
then
    $patient.addBloodTestAnalysis($testType);
end;


rule "Request blood tests for Rheumatoid Arthritis"
	agenda-group "blood tests"
when
    $patient : Patient()
    $symptoms : List()
    $disease : Disease(name == "RA") from allDiseases
    $count : Number() from accumulate(
        $symptom : Symptoms(this memberOf $disease.getSymptoms()) from $symptoms,
        count($symptom)
    )
    eval($count.doubleValue() >= 1)
    $testType : BloodTestType() from $disease.getBloodTests()
    not(exists BloodTestAnalysis(type == $testType, date == LocalDate.now()) from $patient.getBloodTestAnalyses())
then
    $patient.addBloodTestAnalysis($testType);
end;


rule "Request blood tests for Type 1 Diabetes"
when
    $patient : Patient()
    $symptoms : List()
    $disease : Disease(name == "Diabetes Type 1") from allDiseases
    $count : Number() from accumulate(
        $symptom : Symptoms(this memberOf $disease.getSymptoms()) from $symptoms,
        count($symptom)
    )
    eval($count.doubleValue() >= 1)
    $testType : BloodTestType() from $disease.getBloodTests()
    not(exists BloodTestAnalysis(type == $testType, date == LocalDate.now()) from $patient.getBloodTestAnalyses())
then
    $patient.addBloodTestAnalysis($testType);
end;

